"""CIP / EtherNet-IP wire codec — L0 layer (I/O-FORBIDDEN).

This package is the pure, sans-I/O codec core. No layer in this package
may import socket, ssl, asyncio, anyio, selectors, socketserver, http,
urllib, or requests.
"""

from daedalus.cip.constants import (
    EXTENDED_SYMBOL,
    HEADER_SIZE,
    INSUFFICIENT_PACKETS,
    PRIORITY,
    STRUCTURE_READ_REPLY,
    SUCCESS,
    TIMEOUT_MULTIPLIER,
    TIMEOUT_TICKS,
    TRANSPORT_CLASS,
)
from daedalus.cip.custom_types import (
    FixedSizeString,
    IPAddress,
    ListIdentityObject,
    ModuleIdentityObject,
    Revision,
)
from daedalus.cip.data_types import (
    BOOL,
    BYTE,
    DATA_TYPES_BY_CODE,
    DATA_TYPES_BY_NAME,
    DATE,
    DATE_AND_TIME,
    DINT,
    DT,
    DWORD,
    ENGUNIT,
    EPATH_TYPE,
    FTIME,
    INT,
    ITIME,
    LDT,
    LINT,
    LOGIX_STRING,
    LREAL,
    LTIME,
    LWORD,
    REAL,
    SHORT_STRING,
    SINT,
    STIME,
    STRING,
    STRING2,
    STRINGI,
    STRINGN,
    TIME,
    TIME32,
    TIME_OF_DAY,
    UDINT,
    UINT,
    ULINT,
    USINT,
    WORD,
    Array,
    ArrayType,
    DataType,
    DateAndTimeValue,
    DerivedDataType,
    ElementaryDataType,
    StringDataType,
    StringIEntry,
    Struct,
    StructType,
)
from daedalus.cip.object_library import (
    Attribute,
    ClassCode,
    CommonClassAttributes,
    ConnectionManagerInstance,
    FileObjectClassAttributes,
    FileObjectInstance,
    FileObjectInstanceAttributes,
    IdentityObjectInstanceAttributes,
)
from daedalus.cip.segments import (
    EPATH,
    PACKED_EPATH,
    PADDED_EPATH,
    CIPSegment,
    DataSegment,
    LogicalSegment,
    PortSegment,
)
from daedalus.cip.services import (
    MULTI_PACKET_SERVICES,
    CIPService,
    ConnectionManagerService,
    EncapsulationCommand,
    FileObjectService,
)
from daedalus.cip.status import (
    EXTEND_CODES,
    EXTERNAL_ACCESS,
    KEYSWITCH,
    PCCC_ERROR_CODE,
    PRODUCT_TYPES,
    SERVICE_STATUS,
    STATES,
    STATUS,
    VENDOR_IDS,
    VENDORS,
    decode_status,
    get_vendor,
)

__all__ = [
    # data types — elementary
    "BOOL",
    "BYTE",
    # data type registries
    "DATA_TYPES_BY_CODE",
    "DATA_TYPES_BY_NAME",
    "DATE",
    "DATE_AND_TIME",
    "DINT",
    "DT",
    "DWORD",
    "ENGUNIT",
    "EPATH",
    "EPATH_TYPE",
    "EXTENDED_SYMBOL",
    "EXTEND_CODES",
    # status tables
    "EXTERNAL_ACCESS",
    "FTIME",
    # constants
    "HEADER_SIZE",
    "INSUFFICIENT_PACKETS",
    "INT",
    "ITIME",
    "KEYSWITCH",
    "LDT",
    "LINT",
    "LOGIX_STRING",
    "LREAL",
    "LTIME",
    "LWORD",
    "MULTI_PACKET_SERVICES",
    "PACKED_EPATH",
    "PADDED_EPATH",
    "PCCC_ERROR_CODE",
    "PRIORITY",
    "PRODUCT_TYPES",
    "REAL",
    "SERVICE_STATUS",
    "SHORT_STRING",
    "SINT",
    "STATES",
    "STATUS",
    "STIME",
    "STRING",
    "STRING2",
    "STRINGI",
    "STRINGN",
    "STRUCTURE_READ_REPLY",
    "SUCCESS",
    "TIME",
    "TIME32",
    "TIMEOUT_MULTIPLIER",
    "TIMEOUT_TICKS",
    "TIME_OF_DAY",
    "TRANSPORT_CLASS",
    "UDINT",
    "UINT",
    "ULINT",
    "USINT",
    "VENDORS",
    "VENDOR_IDS",
    "WORD",
    "Array",
    "ArrayType",
    # object library
    "Attribute",
    # segments
    "CIPSegment",
    "CIPService",
    "ClassCode",
    "CommonClassAttributes",
    "ConnectionManagerInstance",
    "ConnectionManagerService",
    "DataSegment",
    # data types — base
    "DataType",
    "DateAndTimeValue",
    "DerivedDataType",
    "ElementaryDataType",
    # services
    "EncapsulationCommand",
    "FileObjectClassAttributes",
    "FileObjectInstance",
    "FileObjectInstanceAttributes",
    "FileObjectService",
    "FixedSizeString",
    # custom types
    "IPAddress",
    "IdentityObjectInstanceAttributes",
    "ListIdentityObject",
    "LogicalSegment",
    "ModuleIdentityObject",
    "PortSegment",
    "Revision",
    "StringDataType",
    "StringIEntry",
    "Struct",
    "StructType",
    "decode_status",
    "get_vendor",
]
